# Generated by Django 3.2.7 on 2021-09-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_city_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='city',
            name='temprature',
        ),
    ]
