# Generated by Django 3.2.7 on 2021-09-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_auto_20210930_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
